sudo: required
services:
  - docker

before_install:
  - from encrypted process
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-acount --key-file service-account.json
  - gcloud config set project [project id]
  - gcloud config set cpmpute/zone [zone]
  - gcloud container clusters get-credentials [cluster name]
  - echo "$DOCKER_PASSWD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push bigoyang/F1_proxy:0.1.0
  
script:
  - docker build -t bigoyang/F1_proxy:0.1.0 ./services/proxy
  
after_success:
  - echo "$DOCKER_PASSWD" | docker login -u "$DOCKER_ID"
  - docker push bigoyang/F1_proxy:0.1.0

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
